Repository AY2425S2-CS2103-F09-3/tp, pull requests merged in 2025-04, with the labels that each got.

#138 Resolve alpha bugs for import feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/CsvParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/VcfParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CsvParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/VcfParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug

#125 Validate export filename and improve messages
  new.vcf
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/storage/CsvAddressBookStorage.java
  src/main/java/seedu/address/storage/VcfAddressBookStorage.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/storage/CsvAddressBookStorageTest.java
  src/test/java/seedu/address/storage/VcfAddressBookStorageTest.java
  test2.csv
  testing.csv
  v.vcf
Labels: type.Bug

#127 Improve sort error message
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Bug

#136 Add defensive code and logging for export feature
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/storage/CsvAddressBookStorage.java
  src/main/java/seedu/address/storage/VcfAdaptedPerson.java
  src/main/java/seedu/address/storage/VcfAddressBookStorage.java
  src/main/java/seedu/address/storage/VcfMapper.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Enhancement, type.Task

#150 Update ug and dg for sort and contact
  docs/DeveloperGuide.md
  docs/diagrams/ContactCommand.puml
  docs/diagrams/SortCommandParser.puml
Labels: type.Task

#142 Update UG
  docs/UserGuide.md
Labels: type.Task

#151 Update DG and UG for export
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
Labels: type.Task

#133 Update deletetag command to deletewithtag
  bin/main/seedu/address/MainApp.class
  bin/main/seedu/address/logic/commands/DeleteAllWithTagCommand.class
  bin/main/seedu/address/logic/commands/EditCommand$EditPersonDescriptor.class
  bin/main/seedu/address/logic/commands/EditCommand.class
  bin/main/seedu/address/logic/parser/AddCommandParser.class
  bin/main/seedu/address/logic/parser/AddressBookParser.class
  bin/main/seedu/address/logic/parser/DeleteAllWithTagCommandParser.class
  bin/main/seedu/address/logic/parser/FindCommandParser.class
  bin/main/seedu/address/model/person/Person.class
  bin/main/seedu/address/model/util/SampleDataUtil.class
  bin/main/seedu/address/storage/CsvAdaptedPerson.class
  bin/main/seedu/address/storage/JsonAdaptedPerson.class
  bin/main/seedu/address/ui/PersonCard.class
  bin/test/seedu/address/commons/util/ConfigUtilTest.class
  bin/test/seedu/address/logic/LogicManagerTest$1.class
  bin/test/seedu/address/logic/LogicManagerTest.class
  bin/test/seedu/address/logic/commands/CommandTestUtil.class
  bin/test/seedu/address/logic/commands/EditPersonDescriptorTest.class
  bin/test/seedu/address/logic/commands/ExportCommandTest.class
  bin/test/seedu/address/logic/commands/FindCommandTest.class
  bin/test/seedu/address/logic/commands/ImportCommandTest.class
  bin/test/seedu/address/logic/parser/AddCommandParserTest.class
  bin/test/seedu/address/logic/parser/AddressBookParserTest.class
  bin/test/seedu/address/logic/parser/ContactCommandParserTest.class
  bin/test/seedu/address/logic/parser/DeleteAllWithTagCommandParserTest.class
  bin/test/seedu/address/logic/parser/FindCommandParserTest.class
  bin/test/seedu/address/model/person/PersonTest.class
  bin/test/seedu/address/storage/CsvAdaptedPersonTest.class
  bin/test/seedu/address/storage/JsonAdaptedPersonTest.class
  bin/test/seedu/address/storage/JsonUserPrefsStorageTest.class
  bin/test/seedu/address/storage/StorageManagerTest.class
  bin/test/seedu/address/storage/VcfAdaptedPersonTest.class
  bin/test/seedu/address/storage/VcfAddressBookStorageTest.class
  bin/test/seedu/address/storage/VcfMapperTest.class
  bin/test/seedu/address/storage/VcfSerializableAddressBookTest.class
  bin/test/seedu/address/testutil/EditPersonDescriptorBuilder.class
  bin/test/seedu/address/testutil/PersonBuilder.class
  bin/test/seedu/address/testutil/PersonUtil.class
  src/main/java/seedu/address/logic/commands/DeleteAllWithTagCommand.java
Labels: type.Bug, priority.Low

#157 Update sort command UG
  docs/UserGuide.md
Labels: type.Task

#154 Fix checkstyle errors
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/RoleContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Checkstyle

#132 Add validation checks for name, role, tag input
  .gitignore
  bin/test/seedu/address/storage/VcfAddressBookStorageTest.class
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Bug

#165 Update seq diagram for sort and contact
  docs/diagrams/ContactCommand.puml
  docs/diagrams/SortCommandParser.puml
Labels: type.Task

#144 Add FindCommand seqDiagram
  .gitignore
  bin/test/seedu/address/storage/VcfAdaptedPersonTest.class
  bin/test/seedu/address/storage/VcfAddressBookStorageTest.class
  bin/test/seedu/address/storage/VcfMapperTest.class
  bin/test/seedu/address/storage/VcfSerializableAddressBookTest.class
  docs/diagrams/.idea/.gitignore
  docs/diagrams/.idea/checkstyle-idea.xml
  docs/diagrams/.idea/misc.xml
  docs/diagrams/.idea/modules.xml
  docs/diagrams/.idea/vcs.xml
  docs/diagrams/InnerFindCommandParser.puml
  docs/diagrams/arePrefixesPresent.puml
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Task

#145 Update ug and dg for deletewithtag and FindCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/.idea/workspace.xml
Labels: type.Task

#166 Update UG with Duplicate Detection Information
  docs/UserGuide.md
Labels: type.Task

#168 update DG
  docs/DeveloperGuide.md
Labels: type.Task

#170 update UG
  docs/UserGuide.md
Labels: type.Task

#172 update DG
  docs/DeveloperGuide.md
Labels: type.Task

#244 Enhance address validation
  src/main/java/seedu/address/model/person/Address.java
Labels: type.Bug, priority.High, severity.High

#248 UG/DG updates
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/PhoneNumberContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/VcfParserTest.java
Labels: alpha-bug, documentationBug

#252 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#253 Check for export file exist
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Enhancement
