Repository AY2425S2-CS2103-F09-3/tp, pull requests merged in 2025-03, with the labels that each got.

#26 Add more definitions to glossary
  docs/DeveloperGuide.md
Labels: documentation

#27 DeveloperGuide Updates
  docs/DeveloperGuide.md
Labels: documentation

#28 Update index page
  docs/index.md
Labels: documentation

#29 Update DG to add NFR
  docs/DeveloperGuide.md
Labels: type.Task

#34 Update README and product webpage
  README.md
  docs/index.md
Labels: type.Task

#37 Implement sort contacts
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Task

#39 Implement Find command by number
  src/main/java/seedu/address/model/person/PhoneNumberContainsKeywordsPredicate.java
Labels: type.Task

#45 Implement skeleton for export to csv file
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
Labels: type.Story

#46 Implement import feature
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CSVParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
Labels: type.Task

#56 Find command by phone number
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: type.Task

#58 Add support for Export to CSV
  .gitignore
  build.gradle
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/storage/CsvAdaptedPerson.java
  src/main/java/seedu/address/storage/CsvAddressBookStorage.java
  src/main/java/seedu/address/storage/CsvSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/CsvAdaptedPersonTest.java
  src/test/java/seedu/address/storage/CsvAddressBookStorageTest.java
  src/test/java/seedu/address/storage/CsvSerializableAddressBookTest.java
Labels: type.Epic

#60 Add unit test case for sort contacts
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Task

#53 Import feature testing
  address_book.csv
  import_test_files/Typical_Persons_CSV.csv
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CsvParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  test2.csv
Labels: type.Epic

#61 Find command pass test cases
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Task

#71 Feature filter by tag
  bin/main/seedu/address/MainApp.class
  bin/main/seedu/address/logic/Messages.class
  bin/main/seedu/address/logic/commands/ExportCommand.class
  bin/main/seedu/address/logic/commands/FindCommand.class
  bin/main/seedu/address/logic/commands/ImportCommand.class
  bin/main/seedu/address/logic/parser/AddressBookParser.class
  bin/main/seedu/address/logic/parser/ArgumentMultimap.class
  bin/main/seedu/address/logic/parser/CSVParser.class
  bin/main/seedu/address/logic/parser/FindCommandParser.class
  bin/main/seedu/address/logic/parser/ImportCommandParser.class
  bin/main/seedu/address/logic/parser/tempThing.class
  bin/main/seedu/address/model/person/NameContainsKeywordsPredicate.class
  bin/main/seedu/address/model/person/PhoneNumberContainsKeywordsPredicate.class
  bin/main/seedu/address/storage/CsvAdaptedPerson.class
  bin/main/seedu/address/storage/CsvAddressBookStorage.class
  bin/main/seedu/address/storage/CsvSerializableAddressBook.class
  bin/test/seedu/address/logic/commands/ExportCommandTest.class
  bin/test/seedu/address/logic/commands/ImportCommandTest.class
  bin/test/seedu/address/logic/commands/SortCommandTest.class
  bin/test/seedu/address/logic/parser/FindCommandParserTest.class
  bin/test/seedu/address/logic/parser/ImportCommandParserTest.class
  bin/test/seedu/address/logic/parser/SortCommandParserTest.class
  bin/test/seedu/address/model/ModelManagerTest.class
  bin/test/seedu/address/model/person/NameTest.class
  bin/test/seedu/address/model/person/PhoneTest.class
  bin/test/seedu/address/storage/CsvAdaptedPersonTest.class
  bin/test/seedu/address/storage/CsvAddressBookStorageTest.class
  bin/test/seedu/address/storage/CsvSerializableAddressBookTest.class
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagsContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Task

#81 Enable assertions and include logging for import command class
  build.gradle
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: type.Task

#82 Add support for export to vcf files
  build.gradle
  new.vcf
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/storage/VcfAdaptedPerson.java
  src/main/java/seedu/address/storage/VcfAddressBookStorage.java
  src/main/java/seedu/address/storage/VcfMapper.java
  src/main/java/seedu/address/storage/VcfSerializableAddressBook.java
  testing.csv
  v.vcf
Labels: type.Epic

#84 Implement import to vcf feature
  address_book.csv
  build.gradle
  import_test_files/Typical_Persons_CSV.csv
  import_test_files/contacts.vcf
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ContactCommandParser.java
  src/main/java/seedu/address/logic/parser/CsvParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/VcfParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/CsvParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/VcfParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Epic

#92 Add tests for export to vcf function
  src/test/java/seedu/address/storage/VcfAdaptedPersonTest.java
  src/test/java/seedu/address/storage/VcfAddressBookStorageTest.java
  src/test/java/seedu/address/storage/VcfMapperTest.java
  src/test/java/seedu/address/storage/VcfSerializableAddressBookTest.java
Labels: type.Task

#93 Fixing test cases
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Checkstyle

#96 Fix checkstyle errors and test case issues
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RoleTest.java
  src/test/java/seedu/address/storage/CsvAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement

#100 Change version number and resolve test cases
  src/main/java/seedu/address/MainApp.java
  src/test/java/seedu/address/commons/util/ConfigUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Epic

#103 Update sample data for last contacted field
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Epic
